### ISSUE TITLE
有bug?

### ISSUE THREAD

**Issue by pheromone** [lipingruan/react-native-refreshable-useful#1]
我新建工程,使用你的index.js.但是会出现很多问题:
1.无论Android还是iOS,首次进入界面都需要下拉刷新一下.
2.无论Android还是iOS,都无法出现右滑删除界面.
3.iOS无法下拉刷新.
4.Android无法上拉加载.
why?

**Comment by lipingruan** [comment]
请问你是用的哪个版本的RN?
我写这个一直是用的0.28.0-0.29.0版本的.
更新的版本还没有添加支持.

**Comment by lipingruan** [comment]
@pheromone

**Comment by pheromone** [comment]
<img width="465" alt="2017-01-23 12 24 23" src="https://cloud.githubusercontent.com/assets/14305431/22191560/e5744b34-e166-11e6-8e43-a3ba3bdb335c.png">

**Comment by lipingruan** [comment]
@pheromone 
我将最新版本发布到了npm.
你可以使用命令进行安装:
`npm install react-native-refreshable-useful@1.0.7`

example首次进入不自动刷新是因为没有在componentDidMount里写刷新, 现已经加上.
建议使用example下面的swipeout示例, 全部功能都有.
下拉刷新和上拉加载都没问题的.

麻烦你查看一下你的package.json文件, 里面的react-native版本是多少?
我只试用了最高0.29版本.

**Comment by lipingruan** [comment]
@pheromone 
实在抱歉!
我之前文件没上传完.

我将最新版本发布到了npm.
你可以使用命令进行安装:
`npm install react-native-refreshable-useful@1.0.7`

使用滑动菜单需要安装一个依赖包, 我暂时没有将它添加到依赖, 需要你手动安装.

`npm install react-tween-state`

example首次进入不自动刷新是因为没有在componentDidMount里写刷新, 现已经加上.
建议使用example下面的swipeout示例, 全部功能都有, 包括左滑显示菜单.
下拉刷新和上拉加载都没问题的.

麻烦你查看一下你的package.json文件, 里面的react-native版本是多少?
我只试用了最高0.29版本.

**Comment by lipingruan** [comment]
我这边上github很慢, 上传文件一直返回400错误. 如果你还在关注这个项目的话, 推荐你使用最新的npm版本.

**Comment by pheromone** [comment]
恩.谢谢.我再试试看
